In [1]:
from src.data.loader import DLConfig, DataLoader

In [2]:
config = DLConfig(
    data_loc = 'test/data',
    batch_size = 16,
    #_sim_shard = (0, 8),
)
loader = DataLoader('ssv2', config)

AttributeError: 'NoneType' object has no attribute 'xla_device'

In [ ]:
from tqdm import tqdm

for i in tqdm(loader.train_loader()):
    pass

5it [00:21,  5.18s/it]

In [4]:
i[1].shape

torch.Size([16, 32, 3, 224, 224])

In [1]:
from src.data.transforms import HorizontalFlip
import numpy as np

test = np.random.randint(0, 255, (32, 3, 244, 244), np.uint8)
print(test)
h = HorizontalFlip()
test = h(test)

[[[[232  32 102 ... 112 239 221]
   [165 163 173 ... 171  63 237]
   [151  20 224 ... 102 163 108]
   ...
   [ 29 106 183 ...  87 125  56]
   [176   1 146 ... 208  31 142]
   [207 103  41 ...  27  21 162]]

  [[149 200  28 ... 226 113  55]
   [113 160 203 ...   5   1 231]
   [215 205  47 ...  46 247 120]
   ...
   [ 39  50 111 ... 210 146  66]
   [ 53 254 158 ... 131 248 234]
   [175  81 155 ... 219 228  59]]

  [[108 240 234 ... 122  46 128]
   [ 17 105 232 ... 104 130 122]
   [ 94  19 168 ... 245 148  54]
   ...
   [ 29  14 163 ... 224  92  30]
   [251  24  14 ... 249 216 114]
   [ 43 213 217 ... 234  97 145]]]


 [[[ 61 248  66 ... 194  73  44]
   [197  17  33 ... 161 177  83]
   [ 98  77  47 ...  90 228  74]
   ...
   [238 137 193 ...  95 171 205]
   [181 122 180 ...   2 134  92]
   [101 220 181 ... 132 238 165]]

  [[145  34  27 ... 179   7 241]
   [ 73 253  22 ... 236 187  71]
   [ 70 139 235 ... 179  25  71]
   ...
   [148 189 222 ...  25  51 210]
   [140 114  75 ... 119  75  92

In [3]:
h(test)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


array([[[[221, 239, 112, ..., 102,  32, 232],
         [237,  63, 171, ..., 173, 163, 165],
         [108, 163, 102, ..., 224,  20, 151],
         ...,
         [ 56, 125,  87, ..., 183, 106,  29],
         [142,  31, 208, ..., 146,   1, 176],
         [162,  21,  27, ...,  41, 103, 207]],

        [[ 55, 113, 226, ...,  28, 200, 149],
         [231,   1,   5, ..., 203, 160, 113],
         [120, 247,  46, ...,  47, 205, 215],
         ...,
         [ 66, 146, 210, ..., 111,  50,  39],
         [234, 248, 131, ..., 158, 254,  53],
         [ 59, 228, 219, ..., 155,  81, 175]],

        [[128,  46, 122, ..., 234, 240, 108],
         [122, 130, 104, ..., 232, 105,  17],
         [ 54, 148, 245, ..., 168,  19,  94],
         ...,
         [ 30,  92, 224, ..., 163,  14,  29],
         [114, 216, 249, ...,  14,  24, 251],
         [145,  97, 234, ..., 217, 213,  43]]],


       [[[ 44,  73, 194, ...,  66, 248,  61],
         [ 83, 177, 161, ...,  33,  17, 197],
         [ 74, 228,  90, ..., 

In [1]:
from transformers import ViTModel
import jax.numpy as jnp

mod = ViTModel.from_pretrained('google/vit-huge-patch14-224-in21k')
sd = mod.state_dict()
for k, v in sd.items():
    sd[k] = jnp.array(v.numpy())

2023-10-05 00:57:03.728985: W pjrt_plugin/src/mps_client.cc:534] WARNING: JAX Apple GPU support is experimental and not all JAX functionality is correctly supported!


Metal device set to: Apple M2


In [2]:
from safetensors.numpy import save_file

save_file(sd, 'vit-huge-14-224.safetensors')